name: vio
max_epochs: 40
accelerator: gpu
devices: 1
batch_size: 8
num_workers: 0
run_profiler: True

datasets:
  - target_height: 448
    target_width: 640
    crop_top: 16
    crop_bottom: 16
    scale: 1.0
    root_dir: "/datasets/vio_mcap/uzh"
  - target_height: 448
    target_width: 640
    crop_top: 0
    crop_bottom: 0
    scale: 1.069
    root_dir: "/datasets/vio_mcap/eth"

model:
  lr: 1e-4
  in_ch: 3
  res_block_ch: [32, 64, 128, 256, 384]
  num_attn_blocks: 12
  adv_weight: 0.01
